#pragma once

#include "network.hpp"
#include "training_blob.hpp"
#include "prediction_blob.hpp"
#include "optimizable_weights.hpp"
#include "techniques/fully_connected.hpp"
#include "techniques/convolutional.hpp"
#include "techniques/max_pool.hpp"
#include "techniques/logistic.hpp"
#include "techniques/tanh.hpp"
#include "techniques/relu.hpp"
#include "techniques/leaky_relu.hpp"
#include "techniques/squared_loss.hpp"
#include "techniques/softmax_cross_entropy.hpp"
#include "techniques/logistic_cross_entropy.hpp"
#include "techniques/sgd.hpp"